---
title: "Manifest File"

filters:
  - sorting-hat
  - ripper
extensions:
  sorting-hat:
    keep:
      - yaml
  ripper:
    include-yaml: false
    output-name: "create_manifest"
    output-dir: "../src/stagecoach"
    script-links-position: "none"
format: gfm
---

The manifest file is a YAML file that describes the
terms of use for a dataset. It includes some simple
automated checks to ensure that your project is
compliant with the terms of use. The terms of use
are as follows:

- You must be a person in the frontier

- You must be working in the town of the frontier

- Your project must have a git repository

- Your project must have a name and a description

This is easily translatable to a couple of simple checks.

First, we import the `Sheriff` class from the `sheriff` module. Then, we create an instance of the `Sheriff` class and call the `check_citizen` method to perform the checks.

If the sheriff verifies citizenship, the checks will pass.

```{python}
from sheriff import sheriff

stagecoach_sheriff = sheriff.Sheriff()
citizen_ok = stagecoach_sheriff.check_citizen()
```

Now that we know that the user is a citizen, we can
check that they are working in a designated [`town`](#TODO create town documentation).

Finally, we can implement the manifest. It's going to be simple
for now, but what it really needs to know is where IT is,
and where the data is, and figure out how to get the data
to the user's specified location.

```{python}
from pyprojroot import here
import yaml

manifest = {
    "frontier": {
        # the name of the frontier may be used in future
        "name": "golden-lab",
        # the version may be used in future
        "schema_version": 1,

        # critical: we must know where the frontier starts
        "root": "/n/holylabs/cgolden_lab/Lab/frontier"
    },
    "paths": {
        # this is the general structure of the frontier
        "goldmine": "goldmine",
        "works": "works",
        "town": "town",
        "governance": "governance"
    },
    # we only have two compute options for now, but this may expand in the future
    "compute": {
        "fasrc": True,
        "local": True
    },
    # FILL IN THE BELOW SECTIONS WITH THE NECESSARY INFORMATION TO GET ACCESS TO THE DATA
    "citizen": {

        # your name must match your name in town
        "name": "",

        # email may be used in future for authentications
        "email": "",

        # this must match the name of your project repository
        "project_name": "",

        # must match above
        "project_working_dir": "",

        # this is the name of the folder that stagecoach will ferry 
        # your input data to
        "input_data_dir": "",

        # this is the name of the folder that stagecoach
        # will ferry your output data from;
        # only necessary if you want to ferry output data back to the frontier,
        # eg via globus
        "output_data_dir": "",

        # globus credentials for ferrying data to and from the frontier; only necessary if you want to ferry data to and from the frontier via globus
        "globus_username": "",
        "globus_endpoint": ""
    }
}

yaml_manifest = yaml.dump(manifest)

output_path = here() / "src" / "stagecoach" / "manifest.yml"

with open(output_path, "w") as f:
    f.write(yaml_manifest)
```


If a citizen can pass the citizenship check, then 
the stagecoach can issue a manifest which the user can fill in
with the necessary information to get access to the data.
